export default [
  {
    login: "jorgepedret",
    id: 437440,
    node_id: "MDQ6VXNlcjQzNzQ0MA==",
    avatar_url: "https://avatars.githubusercontent.com/u/437440?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jorgepedret",
    html_url: "https://github.com/jorgepedret",
    followers_url: "https://api.github.com/users/jorgepedret/followers",
    following_url:
      "https://api.github.com/users/jorgepedret/following{/other_user}",
    gists_url: "https://api.github.com/users/jorgepedret/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/jorgepedret/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jorgepedret/subscriptions",
    organizations_url: "https://api.github.com/users/jorgepedret/orgs",
    repos_url: "https://api.github.com/users/jorgepedret/repos",
    events_url: "https://api.github.com/users/jorgepedret/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jorgepedret/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "charlenopires",
    id: 1365,
    node_id: "MDQ6VXNlcjEzNjU=",
    avatar_url: "https://avatars.githubusercontent.com/u/1365?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/charlenopires",
    html_url: "https://github.com/charlenopires",
    followers_url: "https://api.github.com/users/charlenopires/followers",
    following_url:
      "https://api.github.com/users/charlenopires/following{/other_user}",
    gists_url: "https://api.github.com/users/charlenopires/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/charlenopires/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/charlenopires/subscriptions",
    organizations_url: "https://api.github.com/users/charlenopires/orgs",
    repos_url: "https://api.github.com/users/charlenopires/repos",
    events_url: "https://api.github.com/users/charlenopires/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/charlenopires/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jonezy",
    id: 6587,
    node_id: "MDQ6VXNlcjY1ODc=",
    avatar_url: "https://avatars.githubusercontent.com/u/6587?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jonezy",
    html_url: "https://github.com/jonezy",
    followers_url: "https://api.github.com/users/jonezy/followers",
    following_url: "https://api.github.com/users/jonezy/following{/other_user}",
    gists_url: "https://api.github.com/users/jonezy/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jonezy/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jonezy/subscriptions",
    organizations_url: "https://api.github.com/users/jonezy/orgs",
    repos_url: "https://api.github.com/users/jonezy/repos",
    events_url: "https://api.github.com/users/jonezy/events{/privacy}",
    received_events_url: "https://api.github.com/users/jonezy/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jchristopher",
    id: 10412,
    node_id: "MDQ6VXNlcjEwNDEy",
    avatar_url: "https://avatars.githubusercontent.com/u/10412?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jchristopher",
    html_url: "https://github.com/jchristopher",
    followers_url: "https://api.github.com/users/jchristopher/followers",
    following_url:
      "https://api.github.com/users/jchristopher/following{/other_user}",
    gists_url: "https://api.github.com/users/jchristopher/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/jchristopher/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/jchristopher/subscriptions",
    organizations_url: "https://api.github.com/users/jchristopher/orgs",
    repos_url: "https://api.github.com/users/jchristopher/repos",
    events_url: "https://api.github.com/users/jchristopher/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jchristopher/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "goatslacker",
    id: 10632,
    node_id: "MDQ6VXNlcjEwNjMy",
    avatar_url: "https://avatars.githubusercontent.com/u/10632?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/goatslacker",
    html_url: "https://github.com/goatslacker",
    followers_url: "https://api.github.com/users/goatslacker/followers",
    following_url:
      "https://api.github.com/users/goatslacker/following{/other_user}",
    gists_url: "https://api.github.com/users/goatslacker/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/goatslacker/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/goatslacker/subscriptions",
    organizations_url: "https://api.github.com/users/goatslacker/orgs",
    repos_url: "https://api.github.com/users/goatslacker/repos",
    events_url: "https://api.github.com/users/goatslacker/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/goatslacker/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "sxalexander",
    id: 19952,
    node_id: "MDQ6VXNlcjE5OTUy",
    avatar_url: "https://avatars.githubusercontent.com/u/19952?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sxalexander",
    html_url: "https://github.com/sxalexander",
    followers_url: "https://api.github.com/users/sxalexander/followers",
    following_url:
      "https://api.github.com/users/sxalexander/following{/other_user}",
    gists_url: "https://api.github.com/users/sxalexander/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/sxalexander/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sxalexander/subscriptions",
    organizations_url: "https://api.github.com/users/sxalexander/orgs",
    repos_url: "https://api.github.com/users/sxalexander/repos",
    events_url: "https://api.github.com/users/sxalexander/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/sxalexander/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "rwaldron",
    id: 27985,
    node_id: "MDQ6VXNlcjI3OTg1",
    avatar_url: "https://avatars.githubusercontent.com/u/27985?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/rwaldron",
    html_url: "https://github.com/rwaldron",
    followers_url: "https://api.github.com/users/rwaldron/followers",
    following_url:
      "https://api.github.com/users/rwaldron/following{/other_user}",
    gists_url: "https://api.github.com/users/rwaldron/gists{/gist_id}",
    starred_url: "https://api.github.com/users/rwaldron/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/rwaldron/subscriptions",
    organizations_url: "https://api.github.com/users/rwaldron/orgs",
    repos_url: "https://api.github.com/users/rwaldron/repos",
    events_url: "https://api.github.com/users/rwaldron/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/rwaldron/received_events",
    type: "User",
    site_admin: false,
  },
];
