export default {
  login: "5thComrade",
  id: 47243179,
  node_id: "MDQ6VXNlcjQ3MjQzMTc5",
  avatar_url: "https://avatars.githubusercontent.com/u/47243179?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/5thComrade",
  html_url: "https://github.com/5thComrade",
  followers_url: "https://api.github.com/users/5thComrade/followers",
  following_url:
    "https://api.github.com/users/5thComrade/following{/other_user}",
  gists_url: "https://api.github.com/users/5thComrade/gists{/gist_id}",
  starred_url: "https://api.github.com/users/5thComrade/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/5thComrade/subscriptions",
  organizations_url: "https://api.github.com/users/5thComrade/orgs",
  repos_url: "https://api.github.com/users/5thComrade/repos",
  events_url: "https://api.github.com/users/5thComrade/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/5thComrade/received_events",
  type: "User",
  site_admin: false,
  name: "Antony Chiramel",
  company: "Active Backlogs",
  blog: "https://helloantony.in/",
  location: "Bengaluru",
  email: "antonychiramel07@gmail.com",
  hireable: true,
  bio:
    "I am a Frontend Web Developer and a Serverless functions enthusiast. I code your ideas into minimum viable software products. Visit my website to know more.",
  twitter_username: null,
  public_repos: 39,
  public_gists: 1,
  followers: 562,
  following: 15,
  created_at: "2019-02-01T10:18:16Z",
  updated_at: "2021-03-11T07:30:03Z",
};
